### ISSUE TITLE
SqlSetup: PrepareFailoverCluster throws error

### ISSUE THREAD

**Issue by SepehrCloud** [dsccommunity/SqlServerDsc#1637]
#### Details of the scenario you tried and the problem that is occurring
I've tried to use SqlSetup module with Action:PrepareFailoverCluster. It goes through installation, but at some point fails with an error saying it's not able to connect to SQL Server on the target node. It sounds to be a bug in implementation, because even after PrepareFailoverCluster is completed, we still don't have the FCI cluster up and running, and certainly the MSSQL service would be in stopped mode. Therefore, it is strange that the module is trying to connect to the instance.
#### Verbose logs showing the problem
VERBOSE: [SQLFSX1]:                            [[SqlSetup]InstallFCINode1] Connecting as current user 'CONTOSO\Administrator' using integrated security. (SQLCOMMON0054)
VERBOSE: [SQLFSX1]: LCM:  [ End    Set      ]  [[SqlSetup]InstallFCINode1]  in 295.5100 seconds.
PowerShell DSC resource DSC_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Failed to connect to SQL instance 'SQLFSX1'. (SQLCOMMON0019) ---> System.Management.Automation.MethodInvocationException:
Exception calling "Connect" with "0" argument(s): "Failed to connect to server SQLFSX1." ---> Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server SQLFSX1. ---> System.Data.SqlClient.SqlException: A network-related or
instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider,
error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance,
SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(WindowsIdentity impersonatedIdentity)
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
#### Suggested solution to the issue
Seems like PrepareFailoverCluster action is not tested at all. Implementation needs to be fixed.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### SQL Server edition and version the target node is running

MSSQL 2019, Developer Edition
#### SQL Server PowerShell modules present on the target node

None
#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
#### Version of the DSC module that was used

Name         Version Path
----         ------- ----
SqlServerDsc 14.2.1  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\14.2.1\SqlServerDsc.psd1

**Comment by johlju** [comment]
Sounds like a bug, and there are no integration tests for the `PrepareFailoverCluster` action so it that sense it is very untested and can get regression bugs. 🙁 Unit tests should be added for these scenarios so we can catch these and not get regression errors, but I saw that there are no unit tests that tests that action for `Get-TargetResource`. 

This problem is that it calls `Test-TargetResource` at the end of `Set-TargetResource` to verify the installation. 

https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1#L1628-L1632 

The function `Test-TargetResource` in turn calls `Get-TargetResource` and that is what fails. For example when it calls `Get-SqlEngineProperties` that will connect to the instance to get the properties.   

https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1#L204-L205

These types of calls that is dependent on services to be started need to be skipped when the action is `PrepareFailoverCluster` and a unit test should be added to make sure only the expected functions are called..

**Comment by johlju** [comment]
I'm happy to review a PR that fixes this issue.
